### PR TITLE
fix: apply bound for contract address from hash calculation

### LINKED ISSUE #876: calculateContractAddressFromHash
**Describe the bug**
I think the implementation is wrong. The cairo implementation calculates the hash but the modulus it by `const ADDR_BOUND = 2 ** 251 - MAX_STORAGE_ITEM_SIZE;` where `const MAX_STORAGE_ITEM_SIZE = 256;`

### PR DESCRIPTION
**Pull request by penovicp**
## Motivation and Resolution

Resolves #876 

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

### CODE REVIEW

File: src/utils/hash.ts [hunk 1]
```diff
@@ -205,13 +206,14 @@ export function calculateContractAddressFromHash(
...
 
-  return computeHashOnElements([
+  const hash = computeHashOnElements([
     CONTRACT_ADDRESS_PREFIX,
     deployerAddress,
     salt,
     classHash,
     constructorCalldataHash,
   ]);
+  return toHex(BigInt(hash) % ADDR_BOUND);
```
Comment (tabaktoni) [inline src/utils/hash.ts:216]: I am not sure about this return if it will behave the same as Network, but I guess it will also return it to bounded value?

Comment (penovicp) [reply src/utils/hash.ts:216]: I was surprised when the issue was reported since it never popped up, so I checked with [cairo-lang](https://github.com/starkware-libs/cairo-lang/blob/v0.12.3/src/starkware/starknet/common/storage.cairo#L8), [starknet.py](https://github.com/software-mansion/starknet.py/blob/v0.18.3/starknet_py/hash/address.py#L41), and [starknet-rs](https://github.com/xJonathanLEI/starknet-rs/blob/starknet-core/v0.7.2/starknet-core/src/utils.rs#L190). They use the same approach, it just seems the out of bounds values are rare so nobody noticed.
