### PR TITLE
feat: isClassDeclared  createBulkInvocations, fix cairo0 test

### LINKED ISSUE #1209: Failing tests on devnet v0.2.0-rc.x
Due to changes in the blockifier ("A change was made so that re-declaring cairo0 classes also fails with a "already declared" error") integrated into devnet v0.2.0-rc.x  we must go through our tests and apply the logic to circumvent this error 

Job with failing tests:
https://github.com/starknet-io/starknet.js/actions/runs/10507187425/job/29108393106

tests:
-  deploy and test Wallet › simulate transaction - single transaction S0.11.2 › declare tests only on devnet > simulate DECLARE - Cairo 0 Contract
- deploy and test Wallet › Estimate fee bulk & estimate fee › declare tests only on devnet › declare, deploy & multi invoke functions

Error:
` 40: Contract error: {"revert_error":"Class with hash 0x054328a1075b8820eb43caf0caa233923148c983742402dcfc38541dd843d01a is already declared."}`

### PR DESCRIPTION
**Pull request by tabaktoni**
## Motivation and Resolution
Fix #1209

- Implement TransactionType Fix from #1193 to be able to use TS Invocations properly

## Usage related changes

New
 Test if class is already declared from `ContractClassIdentifier`
```ts
provider.isClassDeclared(contractClassIdentifier: ContractClassIdentifier, blockIdentifier?: BlockIdentifier)
```

Build _bulk_ invocations with auto-detect declared class and declare order sort
~~provider.createBulkInvocations(invocations: Invocations)~~
```ts
provider.prepareInvocations(invocations: Invocations)
```

## Checklist:

- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [ ] All tests are passing

### CODE REVIEW

File: src/provider/rpc.ts [hunk 1]
```diff
@@ -570,4 +573,59 @@ export class RpcProvider implements ProviderInterface {
...
+    }
+  }
+
+  /**
+   * Build bulk invocations with auto-detect declared class
+   * 1. Test if class is declared if not declare it preventing already declared class error and not declared class errors
+   * 2. Order declarations first
+   * @param invocations
+   */
+  public async createBulkInvocations(invocations: Invocations) {
```
Comment (penovicp) [inline src/provider/rpc.ts:611]: I would suggest renaming the method, I feel like users might make a mistake and think it's similar to `accountInvocationsFactory()`. Admittedly I haven't come up with a surefire alternative, maybe something like `sanitizeInvocations()`.

File: src/provider/rpc.ts [hunk 2]
```diff
@@ -570,4 +573,59 @@ export class RpcProvider implements ProviderInterface {
...
+      classHash = contractClassIdentifier.classHash;
+    } else {
+      throw Error('contractClassIdentifier type not satisfied');
+    }
+
+    try {
+      const result = await this.getClass(classHash, blockIdentifier);
+      return result instanceof Object;
+    } catch (error) {
+      return false;
```
Comment (penovicp) [inline src/provider/rpc.ts:601]: Could be filtered for instances of `LibraryError` and re-throw otherwise.

**Review by penovicp — APPROVED** [review]
Two minor nitpicks, in general lgtm

File: src/types/lib/index.ts [hunk 3]
```diff
@@ -99,6 +100,11 @@ export type DeclareContractPayload = {
   compiledClassHash?: string;
 };
 
+/**
+ * DeclareContractPayload with classHash or contract defined
+ */
+export type ContractClassIdentifier = DeclareContractPayload | { classHash: string };
```
Comment (PhilippeR26) [inline src/types/lib/index.ts:106]: Why an object containing the classHash? Seems complicated.
I think that the easiest way for the user is something like this :
```typescript
export type ContractClassIdentifier = DeclareContractPayload | BigNumberish;
```

File: src/provider/rpc.ts (hunk 1 above)
Comment (PhilippeR26) [inline src/provider/rpc.ts:611]: I agree with @penovicp ; all these public functions with `bulk` in their names are not understood by the users.
Such names are OK for internal functions, but are problematic for basic users usage.
We have already this problem with `getEstimateFeeBulk` & `parseFeeEstimateBulkResponse`.
My proposal : `buildInvocations`

**Review by PhilippeR26 — COMMENTED** [review]
Just little naming concerns.

File: src/types/lib/index.ts (hunk 3 above)
Comment (tabaktoni) [reply src/types/lib/index.ts:106]: Because it would be ambiguous.
Class can be identified by classHash or by contract, in case of BigNumberish it can be both and non-specific.

Comment (PhilippeR26) [reply src/types/lib/index.ts:106]: For me, a class is only identified by its hash, and nothing else.

Comment (PhilippeR26) [reply src/types/lib/index.ts:106]: And if you have the address of an instance of a class, you have already the answer of question `is classDeclared`? 
It's more than weird to ask if a parent is existing if you have already one of its children....

Comment (tabaktoni) [reply src/types/lib/index.ts:106]: > And if you have the address of an instance of a class, you have already the answer of the question `is classDeclared`. It's more than weird to ask if a parent is existing if you have already one of its children....

Agree, and this does not contain an address. What address are you referring to?

Comment (tabaktoni) [reply src/types/lib/index.ts:106]: It does not deal with **Contract instance** nor addresses, just with **Contract Class** aka. definition classHash

**ContractClassIdentifier is** 

```ts
{
  contract: CompiledContract | string;
  classHash?: string;
  casm?: CompiledSierraCasm;
  compiledClassHash?: string;
};
```
In this case it covers cases for:
1. identifying class from its source code by computing classHash from contract
2. optional zero computing and classHash is already provided
3. less computing by providing optional params for classHash

```ts
or 
{ classHash: string }
```
This case cover providing non-optional classHash

So that in the end, you can get classHash which is in essence ContractClassIdentifier. 

Changing it to 
```ts
export type ContractClassIdentifier = DeclareContractPayload | BigNumberish;
```
In this case, BigNumberish represents classHash but in the source, we used mixed cases sometimes string sometimes BigNumberish.

Solutions:
1.
Another case is that we set ` | { classHash: BigNumberish }`.
This case is less ambiguous and I think we can do it.

2. create `type ClassHashIdentifier: BigNumberish`
and than do:
```ts
export type ContractClassIdentifier = DeclareContractPayload | ClassHashIdentifier;
```

File: src/provider/rpc.ts (hunk 1 above)
Comment (tabaktoni) [reply src/provider/rpc.ts:611]: prepareBulkInvocations ?
prepareInvocations ?

File: src/types/lib/index.ts (hunk 3 above)
Comment (tabaktoni) [reply src/types/lib/index.ts:106]: > For me, a class is only identified by its hash, and nothing else.

Yes but you can provide that classHash or you can provide source code and we can compute classHash from it.
So both source code and classHash are identifiers

**Review by PhilippeR26 — APPROVED** [review]
OK for me.
