### PR TITLE
Fix detection of Abi version in contract with only constructor

### LINKED ISSUE #1242: new CallData fails on contract with constructor only
**Describe the bug**
new CallData fails on contract with constructor only

**To Reproduce**
Compile and supply Abi of following contract

```
#[starknet::contract]
pub mod OnlyConstructor {
    use starknet::ContractAddress;
    use starknet::storage::Map;

    #[storage]
    struct Storage {
        names: Map::<ContractAddress, felt252>,
    }

    #[constructor]
    fn constructor(ref self: ContractState, name: felt252, address: ContractAddress) {
        self.names.write(address, name);
    }
}
```

**Expected behavior**
successful object creation.

**Screenshots**

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version v20.13.1
- Starknet.js version
- Network [devnet]

**Additional context**

### PR DESCRIPTION
**Pull request by taco-paco**
## Motivation and Resolution
Fixes detection of Abi version and closes #1242 

### RPC version (if applicable)

...

## Usage related changes

No exception of new CallData in contracts without any function

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

### CODE REVIEW

**Review by penovicp — APPROVED** [review]

File: src/utils/calldata/cairo.ts [hunk 1]
```diff
@@ -203,14 +203,16 @@ export function getAbiContractVersion(abi: Abi): ContractVersion {
 
   // determine by function io types "Cairo 1.1" or "Cairo 0.0"
   // find first function with inputs or outputs
-  const testFunction = abi.find(
-    (it) => it.type === 'function' && (it.inputs.length || it.outputs.length)
+  const testSubject = abi.find(
+    (it) =>
+      (it.type === 'function' || it.type === 'constructor') &&
```
Comment (ivpavici) [inline src/utils/calldata/cairo.ts:208]: no need to do it now, but later we can extract these comparisons somewhere to not have magic strings, since we have these same comparisons in a couple of more files cc @penovicp

**Review by ivpavici — APPROVED** [review]
